spring:
  application:
    name: api-rest-transactions
  profiles:
    include:
      - dev
  datasource:
    url: jdbc:postgresql://localhost:5432/pichincha-transactions
    username: postgres
    password: system
  jpa:
    properties:
      hibernate:
        format_sql: false
        default_schema: public
        order_by:
          default_null_ordering: last
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:/db/migration
    validate-on-migrate: true
server:
  port: ${PORT:8080}
  servlet:
    contextPath: /api
  error:
    include-stacktrace: never
    path: never
maxDailyQuote: 1000
